import React from 'react';

type VizProps = {
    data: any;
    type: string; // 'array', 'tree', 'graph'
};

export const Visualizer = ({ data, type }: VizProps) => {
    if (!data) return null;

    if (type === 'array') {
        return (
            <div style={{ display: 'flex', gap: '0.5rem', marginTop: '1.5rem', flexWrap: 'wrap', justifyContent: 'center' }}>
                {data.map((item: number, idx: number) => (
                    <div
                        key={idx}
                        className="animate-slide-up"
                        style={{
                            width: '40px', height: '40px',
                            display: 'flex', alignItems: 'center', justifyContent: 'center',
                            background: 'var(--bg-tertiary)',
                            border: '2px solid var(--border-color)',
                            borderRadius: 'var(--radius-sm)',
                            fontWeight: 600, color: 'var(--text-primary)',
                            boxShadow: 'var(--shadow-sm)',
                            animationDelay: `${idx * 0.1}s`
                        }}
                    >
                        {item}
                    </div>
                ))}
            </div>
        );
    }

    // Placeholder for tree or others
    return (
        <div style={{ marginTop: '1.5rem', textAlign: 'center', color: 'var(--text-tertiary)' }}>
            Interactive {type} visualization generated by AI.
        </div>
    );
};
